name: Terraform Destroy Workflow
 
on:
  workflow_dispatch:  # Allows you to trigger it manually from GitHub UI
 
permissions:
  id-token: write
  contents: write
  pull-requests: write
 
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
 
      # Step 2: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'
 
      # Step 3: Setup Terraform 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
 
      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init -reconfigure
 
      # Step 5: Terraform Destroy
      - name: Terraform Destroy
        run: |
          terraform plan -destroy -out=tf_destroy_plan.tfplan
          terraform apply -auto-approve -lock=false tf_destroy_plan.tfplan
