name: Terraform Deploy
 
on:
  workflow_dispatch
 
jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.10.5

 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
 
      - name: Initialize Terraform
        run: terraform init
 
      - name: Plan Terraform Changes
        run: terraform plan
 
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
